
pipeline { 
	
	agent any

	stages {

    	stage('Simple Print Job') {
       		steps() {
          		script {
            		println "Hello World"
        		}
    		}
  		}
	}
}



testing

testing 2

testing 3

testing 4
